name: Trend Video Publisher

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 05 * * *'  # 09:00 IRST → 05:30 UTC
    - cron: '30 16 * * *'  # 20:00 IRST → 16:30 UTC

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode YouTube cookies
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES_B64 }}" | base64 -d > cookies.txt

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3

      - name: Run main script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          PEXELS_API_KEY:   ${{ secrets.PEXELS_API_KEY }}
          PIXABAY_API_KEY:  ${{ secrets.PIXABAY_API_KEY }}
          COOKIE_FILE: 'cookies.txt'
        run: |
          python main.py > output.txt 2>&1

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: runner-logs-${{ github.run_number }}
          path: output.txt

      - name: Save trends cache
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trends-cache
          path: trends.json
