name: Auto Video Trend Uploader

on:
  workflow_dispatch:   # فعال‌سازی اجرای دستی
  schedule:
    # 10:00 IRST → 06:30 UTC
    - cron: '30 06 * * *'
    # 14:00 IRST → 10:30 UTC
    - cron: '30 10 * * *'
    # 18:00 IRST → 14:30 UTC
    - cron: '30 14 * * *'
    # 21:00 IRST → 17:30 UTC
    - cron: '30 17 * * *'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Run main script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          PEXELS_API_KEY:   ${{ secrets.PEXELS_API_KEY }}
          PIXABAY_API_KEY:  ${{ secrets.PIXABAY_API_KEY }}
        run: python main.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: runner-logs-${{ github.run_number }}
          path: output.txt
