# .github/workflows/scheduler.yml

name: Trend Video Publisher

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 05 * * *'  # 09:00 IRST → 05:30 UTC
    - cron: '30 16 * * *'  # 20:00 IRST → 16:30 UTC

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. بررسی کدها
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. کش pip برای سریع‌تر شدن نصب
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      # 3. نصب پایتون و dependencies
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # ───── نصب و پیکربندی yt-dlp ─────
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3

      # ───── بارگذاری کوکی‌های YouTube ─────
      - name: Setup yt-dlp YouTube cookies
        uses: AnimMouse/setup-yt-dlp/cookies@v3
        with:
          cookies: ${{ secrets.YOUTUBE_COOKIES }}

      # ───── اجرای اسکریپت اصلی ─────
      - name: Run main script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          PEXELS_API_KEY:   ${{ secrets.PEXELS_API_KEY }}
          PIXABAY_API_KEY:  ${{ secrets.PIXABAY_API_KEY }}
        run: |
          python main.py > output.txt 2>&1

      # ───── آپلود لاگ و کش نتایج ─────
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: runner-logs-${{ github.run_number }}
          path: output.txt

      - name: Save trends cache
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trends-cache
          path: trends.json

      # ───── به‌روزرسانی خودکار کوکی‌ها ─────
      - name: Update yt-dlp YouTube cookies
        uses: AnimMouse/setup-yt-dlp/cookies/update@v3
        with:
          cookies_secret_name: YOUTUBE_COOKIES
          token: ${{ secrets.GH_PAT }}   # ← اینجا PAT را فراخوانی می‌کنیم
