name: Download YouTube Video

on:
  push:
    branches:
      - main

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3

      - name: Setup yt-dlp YouTube cookies
        uses: AnimMouse/setup-yt-dlp/cookies@v3
        with:
          cookies: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Download video from YouTube
        continue-on-error: true
        run: |
          yt-dlp --cookies ~/.cache/yt-dlp/youtube/cookies.txt "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
